### ISSUE TITLE
error in data importing 

### ISSUE THREAD

**Issue by tzehuey85** [ranghetti/prismaread#1] opened 2020-11-18 11:58 UTC
Hi, the following error pop out when I tried to input data, 

Error in H5File.open(filename, mode, file_create_pl, file_access_pl) : 
  HDF5-API Errors:
    error #000: c:/msys64/home/Jeroen/hdf5-1.8.16/src/H5F.c in H5Fopen(): line 604: unable to open file
        class: HDF5
        major: File accessibilty
        minor: Unable to open file

    error #001: c:/msys64/home/Jeroen/hdf5-1.8.16/src/H5Fint.c in H5F_open(): line 992: unable to open file: time = Wed Nov 18 19:54:32 2020
, name = 'C:\PRS_L1_STD_OFFL_20190626095645_20190626095650_0001.he5', tent_flags = 1
        class: HDF5
        major: File accessibilty
        minor: Unable to open file

    error #002: c:/msys64/home/Jeroen/hdf5-1.8.16/src/H5FD.c in H5FD_open(): line 993: open failed
        class: HDF5
        major: Virtual File Layer
        minor: Unable to initialize object

    error #003: c:/msys64/home/Jeroen/hdf5-1.8.16/src/H5FDsec2.c in H5FD_sec2_open(): line 339: unable to open file: name = 'C:\PRS_L1_STD_OFFL_20190626095645_20190626095650_0001.he5', errno = 2, error message = 'No such file or directory', flags = 1, o_f        class: HDF5
  
Error in pr_check_inputs(in_file, out_folder, out_filebase, out_format,  : 
  Unable to open the input file as a hdf5 file. Verify your inputs.
           Aborting!

**Comment by ranghetti** [comment] 2020-11-18 12:48
Hi, unfortunately Lorenzo, who developed the package {prismaread}, has recently passed away (https://docs.ropensci.org/MODIStsp/articles/lorenzo.html). I will replace him in the maintainance of the package, but for the moment I do not know the code yet.
For now you can have a look to the documentation at https://lbusett.github.io/prismaread/articles/prismaread .
If this cannot help you to solve, please provide a reproducible example (data and code), and I will have a look to it as soon as I will be confident with the code.

**Comment by ranghetti** [comment] 2020-12-16 08:34
Closing this due to inactivity; if you did not solve by yourself, please reopen the issue and provide a reproducible example (input data and code you launched).

**Comment by sivateja1a9** [comment] 2020-12-25 14:02
Hi ranghetti,
We are also facing the same issue on importing HEF5 file. Could you please suggest us what needs to be done in order to get rid of the issue ?
`Error in H5File.open(filename, mode, file_create_pl, file_access_pl) : 
  HDF5-API Errors:
    error #000: c:/msys64/home/Jeroen/hdf5-1.8.16/src/H5F.c in H5Fopen(): line 604: unable to open file
        class: HDF5
        major: File accessibilty
        minor: Unable to open file

    error #001: c:/msys64/home/Jeroen/hdf5-1.8.16/src/H5Fint.c in H5F_open(): line 992: unable to open file: time = Fri Dec 25 19:07:31 2020
, name = 'F:\ENVIDATA\CHENNARAYAPATNA\0PRISMADATA\PRS_L2D_STD_20200220053445_20200220053449_0001', tent_flags = 1
        class: HDF5
        major: File accessibilty
        minor: Unable to open file

    error #002: c:/msys64/home/Jeroen/hdf5-1.8.16/src/H5FD.c in H5FD_open(): line 993: open failed
        class: HDF5
        major: Virtual File Layer
        minor: Unable to initialize object

    error #003: c:/msys64/home/Jeroen/hdf5-1.8.16/src/H5FDsec2.c in H5FD_sec2_open(): line 339: unable to open file: name = 'F:\ENVIDATA\CHENNARAYAPATNA\0PRISMADATA\PRS_L2D_STD_20200220053445_20200220053449_0001', errno = 13, error message = 'Permi
Error in pr_check_inputs(in_file, out_folder, out_filebase, out_format,  : 
  Unable to open the input file as a hdf5 file. Verify your inputs.
           Aborting!`

**Comment by ranghetti** [comment] 2020-12-25 19:10
Hi @sivateja1a9, as asked to tzehuey85, please provide a reproducible example (input data and code you launched).

**Comment by ranghetti** [comment] 2021-05-20 19:52
Closing due to missing feedback.

**Closed by ranghetti** 2021-05-20 19:52 UTC

**Comment by geomining88** [comment] 2023-08-29 15:06
Hello @ranghetti .

I got these messages when i tried to import a he5 file.

`error #000: D:/a/rtools-packages/rtools-packages/mingw-w64-hdf5/src/hdf5-1.8.16/src/H5F.c in H5Fopen(): line 604: unable to open file`
`Error #001: D:/a/rtools-packages/rtools-packages/mingw-w64-hdf5/src/hdf5-1.8.16/src/H5Fint.c in H5F_open(): line 992: unable to open file: time`
` error #002: D:/a/rtools-packages/rtools-packages/mingw-w64-hdf5/src/hdf5-1.8.16/src/H5FD.c in H5FD_open(): line 993: open failed`
`error #003: D:/a/rtools-packages/rtools-packages/mingw-w64-hdf5/src/hdf5-1.8.16/src/H5FDsec2.c in H5FD_sec2_open(): line 339: unable to open file`

Is there a solution to this problem?

Thank you!
